apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      initContainers:
      - image: busybox
        name: sleep
        command: ["sleep", "120"]
      containers:
      - image: nginx:1.17
        name: nginx
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /
            port: 80
        resources: {}
status: {}
